### ISSUE TITLE
ImportError : cannot import name 'QtWebengineWidgets'

### ISSUE THREAD

**Issue by dbeiner** [saschaludwig/OnAirScreen#24] opened 2020-02-10 23:04 UTC
Hello,

When I do ./start.py I get this message : 

ImportError : cannot import name 'QtWebengineWidgets'

Can you please help me ?

Thank you !

**Comment by saschaludwig** [comment] 2020-02-11 08:25
Duplicate of #20

**Closed by saschaludwig** 2020-02-11 08:25 UTC
